// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw6TEtHlTAcXXgvPab2VqEosl1B_V9ihk',
    appId: '1:227051164396:web:a283f92d37a63c57408bc9',
    messagingSenderId: '227051164396',
    projectId: 'chat-36a62',
    authDomain: 'chat-36a62.firebaseapp.com',
    storageBucket: 'chat-36a62.appspot.com',
    measurementId: 'G-ESCL0NHE1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1rp4XLJicgwxmQjZv3t1ig5iHMBnY06M',
    appId: '1:227051164396:android:952df220680946f3408bc9',
    messagingSenderId: '227051164396',
    projectId: 'chat-36a62',
    storageBucket: 'chat-36a62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJvLn-vmHC6R1bod9bTSSxXdFy_2Z5hfM',
    appId: '1:227051164396:ios:41de9c0715bfe37e408bc9',
    messagingSenderId: '227051164396',
    projectId: 'chat-36a62',
    storageBucket: 'chat-36a62.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJvLn-vmHC6R1bod9bTSSxXdFy_2Z5hfM',
    appId: '1:227051164396:ios:d09b3bb6a0681ddb408bc9',
    messagingSenderId: '227051164396',
    projectId: 'chat-36a62',
    storageBucket: 'chat-36a62.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
